import type { Product } from '@/types';
import { ProductType } from '@/types';

const productList: Product[] = [
    {
        id: 1,
        name: 'Latte',
        price: 3.5,
        type: ProductType.COFFEE,
        size: 300,
        image: 'https://premieremoisson.com/files/produits/800x650/1633094643--979-front-95010-cafe-latt.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 18,
    },
    {
        id: 2,
        name: 'Espreso',
        price: 2.1,
        type: ProductType.COFFEE,
        size: 35,
        image: 'https://premieremoisson.com/files/produits/800x650/1633094402--984-front-95017-cafe-espr.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 5,
    },
    {
        id: 3,
        name: 'Cappuccino',
        price: 2.8,
        type: ProductType.COFFEE,
        size: 150,
        image: 'https://premieremoisson.com/files/produits/800x650/1633093439--981-front-95014-cafe-capp.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 20,
    },
    {
        id: 4,
        name: 'Mocha',
        price: 3.2,
        type: ProductType.COFFEE,
        size: 200,
        image: 'https://premieremoisson.com/files/produits/800x650/1633097167--980-front-95015-cafe-moka.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 13,
    },
    {
        id: 5,
        name: 'Iced Coffee',
        price: 3.2,
        type: ProductType.COFFEE,
        size: 200,
        image: 'https://premieremoisson.com/files/produits/800x650/1683811509--1293-front-cafe-glace-8.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 11,
    },
    {
        id: 6,
        name: 'Americano',
        price: 3.2,
        type: ProductType.COFFEE,
        size: 200,
        image: 'https://premieremoisson.com/files/produits/800x650/1633094787--983-front-95006-cafe-amer.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 4,
    },
    {
        id: 7,
        name: '4 seasons charlotte',
        price: 3.2,
        type: ProductType.DESSERTS,
        size: 200,
        image: 'https://premieremoisson.com/files/produits/800x650/1616523356--779-front-25570-charlotte.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 4,
    },
    {
        id: 8,
        name: 'Creamy quebec strawberry profiterole',
        price: 3.2,
        type: ProductType.DESSERTS,
        size: 100,
        image: 'https://premieremoisson.com/files/produits/800x650/1623242692--728-front-38328-profitero.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 9,
        name: 'Strawberry and mint',
        price: 3.2,
        type: ProductType.DESSERTS,
        size: 100,
        image: 'https://premieremoisson.com/files/produits/800x650/1710782615--1567-front-fraise-et-ment.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 10,
        name: 'Hazelnut passion',
        price: 34,
        type: ProductType.DESSERTS,
        size: 800,
        image: 'https://premieremoisson.com/files/produits/800x650/1710777683--1564-front-passion-noiset.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 11,
        name: 'Jardinière',
        price: 26.50,
        type: ProductType.DESSERTS,
        size: 700,
        image: 'https://premieremoisson.com/files/produits/800x650/1563820494--FRONT--jardiniere.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 12,
        name: 'Lemon pie',
        price: 23.50,
        type: ProductType.DESSERTS,
        size: 500,
        image: 'https://premieremoisson.com/files/produits/800x650/1712259839--246-front-47520-tarte-au.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 13,
        name: 'Chocolate trio',
        price: 5.95,
        type: ProductType.DESSERTS,
        size: 80,
        image: 'https://premieremoisson.com/files/produits/800x650/1710192765--790-front-resize-trio-de.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 14,
        name: 'Half & half millefeuille',
        price: 5.15,
        type: ProductType.DESSERTS,
        size: 65,
        image: 'https://premieremoisson.com/files/produits/800x650/1710192484--226-front-resize-mille-fe.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 15,
        name: 'Seasonal cheesecake',
        price: 6.15,
        type: ProductType.DESSERTS,
        size: 85,
        image: 'https://premieremoisson.com/files/produits/800x650/1710783008--1626-front-gateau-au-from.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 16,
        name: 'Raspberry-pistachio mignon',
        price: 4.15,
        type: ProductType.DESSERTS,
        size: 40,
        image: 'https://premieremoisson.com/files/produits/800x650/1613412092--721-front-20045-mignon-fr.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 17,
        name: 'Meal-sized chicken amour salad',
        price: 15.75,
        type: ProductType.SALADS,
        size: 350,
        image: 'https://premieremoisson.com/files/produits/800x650/1649361261--837-top-26741100000-salad.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 18,
        name: 'Meal-sized greek chick peas salad',
        price: 15.75,
        type: ProductType.SALADS,
        size: 350,
        image: 'https://premieremoisson.com/files/produits/800x650/1649361902--839-top-26741900000-salad.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 19,
        name: 'Tabbouleh',
        price: 15.75,
        type: ProductType.SALADS,
        size: 350,
        image: 'https://premieremoisson.com/files/produits/800x650/1710872169--1608-top-salade-de-taboul.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 20,
        name: 'Farfalle pasta salad with prosciutto arugula and parmesan',
        price: 15.75,
        type: ProductType.SALADS,
        size: 350,
        image: 'https://premieremoisson.com/files/produits/800x650/1630603949--860-top-salade-de-farfall.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    },
    {
        id: 21,
        name: 'Meal-sized salmon with sesame crust salad',
        price: 15.75,
        type: ProductType.SALADS,
        size: 350,
        image: 'https://premieremoisson.com/files/produits/800x650/1648581733--977-top-26740900000-salad.webp',
        description: 'Lorem ipsum dolor sit amet.',
        ordersNumber: 8,
    }
];

export default productList;